baseurl: ""

title      : oobalink Northern Suburbs - Bond Origination & Home Loan Experts in Northern Suburbs, Cape Town, Western Cape, South Africa
email      : antonellawerth@ooba-link.co.za
description: Contact oobalink Northern Suburbs from Durbanville Hills to help you with home loan. We are seasoned property professionals that specialize in mortgages and property finance with 28 years of experience. Our experience ranges from sales to finance and she specializes in bonds, home loans and origination. We are committed to excellent client service, building long-term relationships..
author     : Eben Roux / Pieter Oosthuizen

analytics:
  google: G-ENSV5HFFL3

collections:
  portfolio:

markdown: kramdown

webserver_headers:
  - - Access-Control-Allow-Origin
    - "*"
  - - Access-Control-Allow-Methods
    - GET, OPTIONS, HEAD

logo:
  path: /assets/oobalink logo.png

exclude: [node_modules,webpack-config.js,package.json,package-lock.json]

group: oobalink

company: oobalink Northern Suburbs

url: www.oobalink-ns.co.za

address: 48 Drakenstein Road, Durbanville Hills, Cape Town, 7550
